// Demo data for the platform

export const demoMatches = [
  {
    id: 1,
    league: "Premier League",
    homeTeam: "Manchester City",
    awayTeam: "Liverpool",
    homeScore: 2,
    awayScore: 1,
    status: "live",
    minute: 67,
    time: "",
    homeWinPercent: 58,
    drawPercent: 22,
    awayWinPercent: 20,
    btts: 75,
    over25: 82,
  },
  {
    id: 2,
    league: "Premier League",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    homeScore: 1,
    awayScore: 1,
    status: "live",
    minute: 45,
    time: "",
    homeWinPercent: 45,
    drawPercent: 28,
    awayWinPercent: 27,
    btts: 68,
    over25: 71,
  },
  {
    id: 3,
    league: "La Liga",
    homeTeam: "Real Madrid",
    awayTeam: "Barcelona",
    homeScore: 0,
    awayScore: 0,
    status: "upcoming",
    minute: 0,
    time: "20:00",
    homeWinPercent: 42,
    drawPercent: 26,
    awayWinPercent: 32,
    btts: 72,
    over25: 78,
  },
  {
    id: 4,
    league: "Serie A",
    homeTeam: "Inter Milan",
    awayTeam: "AC Milan",
    homeScore: 0,
    awayScore: 0,
    status: "upcoming",
    time: "18:45",
    homeWinPercent: 48,
    drawPercent: 27,
    awayWinPercent: 25,
    btts: 65,
    over25: 69,
  },
  {
    id: 5,
    league: "Bundesliga",
    homeTeam: "Bayern Munich",
    awayTeam: "Borussia Dortmund",
    homeScore: 3,
    awayScore: 2,
    status: "live",
    minute: 82,
    time: "",
    homeWinPercent: 62,
    drawPercent: 20,
    awayWinPercent: 18,
    btts: 88,
    over25: 91,
  },
  {
    id: 6,
    league: "Ligue 1",
    homeTeam: "PSG",
    awayTeam: "Marseille",
    homeScore: 0,
    awayScore: 0,
    status: "upcoming",
    time: "21:00",
    homeWinPercent: 65,
    drawPercent: 20,
    awayWinPercent: 15,
    btts: 58,
    over25: 73,
  },
]

export const demoArticles = [
  {
    id: 1,
    title: "Manchester City vs Liverpool: Tactical Analysis",
    excerpt:
      "A deep dive into the tactical battle between two Premier League giants. How Guardiola's system matches up against Klopp's high press.",
    author: "John Smith",
    date: "2024-01-15",
    readTime: "5 min read",
    category: "Analysis",
    image: "/football-tactical-analysis.png",
  },
  {
    id: 2,
    title: "Top 5 Strikers to Watch This Season",
    excerpt:
      "Our expert picks for the most lethal forwards in European football right now, based on advanced statistics and performance metrics.",
    author: "Sarah Johnson",
    date: "2024-01-14",
    readTime: "7 min read",
    category: "Features",
    image: "/football-striker-scoring-goal.jpg",
  },
  {
    id: 3,
    title: "El Clásico Preview: Real Madrid vs Barcelona",
    excerpt:
      "Everything you need to know before the biggest match in world football. Form guide, key battles, and our prediction.",
    author: "Carlos Rodriguez",
    date: "2024-01-13",
    readTime: "6 min read",
    category: "Preview",
    image: "/real-madrid-barcelona-el-clasico.jpg",
  },
]

export const matchDetails = {
  1: {
    id: 1,
    league: "Premier League",
    homeTeam: "Manchester City",
    awayTeam: "Liverpool",
    homeScore: 2,
    awayScore: 1,
    status: "live",
    minute: 67,
    stadium: "Etihad Stadium",
    referee: "Michael Oliver",
    attendance: "53,400",
    events: [
      { minute: 12, type: "goal", team: "home", player: "Erling Haaland", assist: "Kevin De Bruyne" },
      { minute: 28, type: "yellow", team: "away", player: "Fabinho" },
      { minute: 34, type: "goal", team: "away", player: "Mohamed Salah", assist: "Trent Alexander-Arnold" },
      { minute: 56, type: "goal", team: "home", player: "Phil Foden", assist: "Jack Grealish" },
      { minute: 62, type: "substitution", team: "away", playerOut: "Darwin Núñez", playerIn: "Diogo Jota" },
    ],
    stats: {
      possession: { home: 58, away: 42 },
      shots: { home: 14, away: 9 },
      shotsOnTarget: { home: 6, away: 4 },
      corners: { home: 7, away: 3 },
      fouls: { home: 8, away: 12 },
      yellowCards: { home: 1, away: 2 },
      redCards: { home: 0, away: 0 },
    },
    form: {
      home: ["W", "W", "D", "W", "W"],
      away: ["W", "L", "W", "W", "D"],
    },
    homeWinPercent: 58,
    drawPercent: 22,
    awayWinPercent: 20,
  },
}
